apiVersion: v1
kind: PersistentVolume
metadata:
  name: email-pv
  namespace: email-ns
spec:
  capacity:
    storage: 300Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: email-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-a30c17a4::fsap-0fd2bde9405ad7253